### ISSUE TITLE
Stop showing in HASS after HASS restart

### ISSUE THREAD

**Issue by chatainsim** [Sennevds/system_sensors#8] opened 2019-09-04 15:06 UTC
Hello,
I have an issue with the script. When I restart Hass, every sensor are gone until I restart each script on each RPI.

**Comment by Sennevds** [comment] 2019-09-10 16:11
Normally it should retain the config. The values itself should automatically update after they are resend by the script

**Comment by chatainsim** [comment] 2019-09-11 09:11
How can I debug this and provide you more informations ?

**Comment by Sennevds** [comment] 2019-09-11 18:02
Restart hass and wait for 10 to 20mins to see if data is updated

**Comment by chatainsim** [comment] 2019-09-11 18:19
Hass has been restarted on September 7th and no system_sensors appears since.
If I restart the system_sensors script then they appear in hass.

**Comment by Sennevds** [comment] 2019-09-11 19:04
And you have the latest script?
Can you connect with a MQTT client and check if there's a config at
following topic:
homeassistant/sensor/"+ deviceName +"/"+ deviceName +"Temp/config

Op wo 11 sep. 2019 om 20:19 schreef Simon <notifications@github.com>:

**Comment by chatainsim** [comment] 2019-09-11 19:42
Yes, I'm using the latest version.
I found in RabbitMQ that the connection was idle since the 4th of september.
I've created one user per running scripts in RabbitMQ then I will follow what's happen.
I'll try to restart Hass and see if issue persist.
I'll keep you posted.

Thanks

**Comment by chatainsim** [comment] 2019-09-11 19:43
RabbitMQ is running on another RPI than the hass one.

**Comment by chatainsim** [comment] 2019-09-13 07:46
I've restarted hass on september 12th and then no more system_sensors in hass.
Message are still sent to RabbitMQ.
So I think this is more an hass issue.
Is there a specific message sent when system_sensors script start ?

**Comment by Sennevds** [comment] 2019-09-13 08:19
Normally you have for eacht sensor and each pi a config message. This message should be retained.
If this message is retained hass should read it at startup recognize it as a device.
You could add mqtt to your log of hass and restart hass and check the messages.
ex log config:
```yaml
logger:
  default: warning
  logs:
    # custom_components.pool_pump_service: info
    homeassistant.components.mqtt: debug
```
in the log you should see something like this:
```log
2019-09-13 10:18:19 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on homeassistant/sensor/Matrix/MatrixTemp/config (retained): b'{ "name": "MatrixTemperature", "state_topic": "homeassistant/sensor/Matrix/state", "unit_of_measurement": "\xc2\xb0C", "value_template": "{{ value_json.temperature}}" }'
2019-09-13 10:18:19 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on homeassistant/sensor/Matrix/MatrixDiskUse/config (retained): b'{ "name": "MatrixDiskUse", "state_topic": "homeassistant/sensor/Matrix/state", "unit_of_measurement": "%", "value_template": "{{ value_json.disk_use}}" }'
2019-09-13 10:18:19 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on homeassistant/sensor/Matrix/MatrixMemoryUse/config (retained): b'{ "name": "MatrixMemoryUse", "state_topic": "homeassistant/sensor/Matrix/state", "unit_of_measurement": "%", "value_template": "{{ value_json.memory_use}}" }'
2019-09-13 10:18:19 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on homeassistant/sensor/Matrix/MatrixCpuUsage/config (retained): b'{ "name": "MatrixCpuUsage", "state_topic": "homeassistant/sensor/Matrix/state", "unit_of_measurement": "%", "value_template": "{{ value_json.cpu_usage}}" }'
2019-09-13 10:18:19 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on homeassistant/sensor/Matrix/MatrixPowerStatus/config (retained): b'{ "name": "MatrixPowerStatus", "state_topic": "homeassistant/sensor/Matrix/state", "value_template": "{{ value_json.power_status}}" }'
```

**Comment by chatainsim** [comment] 2019-09-13 08:41
Here are the log, only one of the three pi appear:
```
2019-09-13 10:36:14 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on homeassistant/sensor/DomoPi/state: b'{"temperature": 47.8, "disk_use":
28.6, "memory_use": 27.4, "cpu_usage": 6.5, "power_status": "Everything is working as intended", "last_boot": "2019-07-30T21:49:49+02:00"}'
2019-09-13 10:36:44 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on homeassistant/sensor/DomoPi/state: b'{"temperature": 48.3, "disk_use":
28.6, "memory_use": 27.4, "cpu_usage": 5.9, "power_status": "Everything is working as intended", "last_boot": "2019-07-30T21:49:49+02:00"}'
2019-09-13 10:37:14 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on homeassistant/sensor/DomoPi/state: b'{"temperature": 48.3, "disk_use":
28.6, "memory_use": 27.4, "cpu_usage": 7.3, "power_status": "Everything is working as intended", "last_boot": "2019-07-30T21:49:49+02:00"}'
2019-09-13 10:37:44 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on homeassistant/sensor/DomoPi/state: b'{"temperature": 48.3, "disk_use":
28.6, "memory_use": 27.5, "cpu_usage": 5.5, "power_status": "Everything is working as intended", "last_boot": "2019-07-30T21:49:49+02:00"}'
2019-09-13 10:38:14 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on homeassistant/sensor/DomoPi/state: b'{"temperature": 48.3, "disk_use":
28.6, "memory_use": 27.3, "cpu_usage": 6.4, "power_status": "Everything is working as intended", "last_boot": "2019-07-30T21:49:49+02:00"}'
2019-09-13 10:38:44 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on homeassistant/sensor/DomoPi/state: b'{"temperature": 48.3, "disk_use":
28.6, "memory_use": 27.4, "cpu_usage": 5.2, "power_status": "Everything is working as intended", "last_boot": "2019-07-30T21:49:49+02:00"}'
2019-09-13 10:39:14 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on homeassistant/sensor/DomoPi/state: b'{"temperature": 48.3, "disk_use":
28.6, "memory_use": 27.4, "cpu_usage": 6.8, "power_status": "Everything is working as intended", "last_boot": "2019-07-30T21:49:49+02:00"}'
2019-09-13 10:39:44 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on homeassistant/sensor/DomoPi/state: b'{"temperature": 48.3, "disk_use":
28.6, "memory_use": 27.4, "cpu_usage": 6.3, "power_status": "Everything is working as intended", "last_boot": "2019-07-30T21:49:49+02:00"}'
2019-09-13 10:40:14 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on homeassistant/sensor/DomoPi/state: b'{"temperature": 48.3, "disk_use":
28.6, "memory_use": 27.3, "cpu_usage": 7.1, "power_status": "Everything is working as intended", "last_boot": "2019-07-30T21:49:49+02:00"}'
2019-09-13 10:40:44 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on homeassistant/sensor/DomoPi/state: b'{"temperature": 48.3, "disk_use":
28.6, "memory_use": 27.4, "cpu_usage": 5.2, "power_status": "Everything is working as intended", "last_boot": "2019-07-30T21:49:49+02:00"}'
2019-09-13 10:41:14 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on homeassistant/sensor/DomoPi/state: b'{"temperature": 48.3, "disk_use":
28.6, "memory_use": 27.4, "cpu_usage": 7.2, "power_status": "Everything is working as intended", "last_boot": "2019-07-30T21:49:
```

**Comment by chatainsim** [comment] 2019-09-13 08:45
After restarting one of them:
```
2019-09-13 10:44:16 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on homeassistant/sensor/RpiHass/RpiHassTemp/config: b'{"name":"RpiHassTemp
erature","state_topic":"system-sensors/sensor/RpiHass/state","unit_of_measurement":"\xc2\xb0C","value_template":"{{ value_json.temperature}}","unique_id":"rpihass
_sensor_temperature","device":{"identifiers":["rpihass_sensor"],"name":"RpiHassSensors","model":"RPI RpiHass","manufacturer":"RPI"}}'
2019-09-13 10:44:16 INFO (MainThread) [homeassistant.components.mqtt.discovery] Found new component: sensor RpiHass RpiHassTemp
2019-09-13 10:44:16 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on homeassistant/sensor/RpiHass/RpiHassDiskUse/config: b'{"name":"RpiHassD
iskUse","state_topic":"system-sensors/sensor/RpiHass/state","unit_of_measurement":"%","value_template":"{{ value_json.disk_use}}","unique_id":"rpihass_sensor_disk
_use","device":{"identifiers":["rpihass_sensor"],"name":"RpiHassSensors","model":"RPI RpiHass","manufacturer":"RPI"}}'
2019-09-13 10:44:16 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on homeassistant/sensor/RpiHass/RpiHassMemoryUse/config: b'{"name":"RpiHas
sMemoryUse","state_topic":"system-sensors/sensor/RpiHass/state","unit_of_measurement":"%","value_template":"{{ value_json.memory_use}}","unique_id":"rpihass_senso
r_memory_use","device":{"identifiers":["rpihass_sensor"],"name":"RpiHassSensors","model":"RPI RpiHass","manufacturer":"RPI"}}'
2019-09-13 10:44:16 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on homeassistant/sensor/RpiHass/RpiHassCpuUsage/config: b'{"name":"RpiHass
CpuUsage","state_topic":"system-sensors/sensor/RpiHass/state","unit_of_measurement":"%","value_template":"{{ value_json.cpu_usage}}","unique_id":"rpihass_sensor_c
pu_usage","device":{"identifiers":["rpihass_sensor"],"name":"RpiHassSensors","model":"RPI RpiHass","manufacturer":"RPI"}}'
2019-09-13 10:44:16 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on homeassistant/sensor/RpiHass/RpiHassSwapUsage/config: b'{"name":"RpiHas
sSwapUsage","state_topic":"system-sensors/sensor/RpiHass/state","unit_of_measurement":"%","value_template":"{{ value_json.swap_usage}}","unique_id":"rpihass_senso
r_swap_usage","device":{"identifiers":["rpihass_sensor"],"name":"RpiHassSensors","model":"RPI RpiHass","manufacturer":"RPI"}}'
2019-09-13 10:44:16 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on homeassistant/sensor/RpiHass/RpiHassPowerStatus/config: b'{"name":"RpiH
assPowerStatus","state_topic":"system-sensors/sensor/RpiHass/state","value_template":"{{ value_json.power_status}}","unique_id":"rpihass_sensor_power_status","dev
ice":{"identifiers":["rpihass_sensor"],"name":"RpiHassSensors","model":"RPI RpiHass","manufacturer":"RPI"}}'
2019-09-13 10:44:16 INFO (MainThread) [homeassistant.components.mqtt.discovery] Found new component: sensor RpiHass RpiHassDiskUse
2019-09-13 10:44:16 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on homeassistant/sensor/RpiHass/RpiHassLastBoot/config: b'{"device_class":
"timestamp","name":"RpiHassLastBoot","state_topic":"system-sensors/sensor/RpiHass/state","value_template":"{{ value_json.last_boot}}","unique_id":"rpihass_sensor_
last_boot","device":{"identifiers":["rpihass_sensor"],"name":"RpiHassSensors","model":"RPI RpiHass","manufacturer":"RPI"}}'
2019-09-13 10:44:16 INFO (MainThread) [homeassistant.components.mqtt.discovery] Found new component: sensor RpiHass RpiHassMemoryUse
2019-09-13 10:44:16 INFO (MainThread) [homeassistant.components.mqtt.discovery] Found new component: sensor RpiHass RpiHassCpuUsage
2019-09-13 10:44:16 INFO (MainThread) [homeassistant.components.mqtt.discovery] Found new component: sensor RpiHass RpiHassSwapUsage
2019-09-13 10:44:16 INFO (MainThread) [homeassistant.components.mqtt.discovery] Found new component: sensor RpiHass RpiHassPowerStatus
2019-09-13 10:44:16 INFO (MainThread) [homeassistant.components.mqtt.discovery] Found new component: sensor RpiHass RpiHassLastBoot
2019-09-13 10:44:16 DEBUG (MainThread) [homeassistant.components.mqtt] Subscribing to system-sensors/sensor/RpiHass/state
2019-09-13 10:44:16 DEBUG (MainThread) [homeassistant.components.mqtt] Subscribing to system-sensors/sensor/RpiHass/state
2019-09-13 10:44:16 DEBUG (MainThread) [homeassistant.components.mqtt] Subscribing to system-sensors/sensor/RpiHass/state
2019-09-13 10:44:16 DEBUG (MainThread) [homeassistant.components.mqtt] Subscribing to system-sensors/sensor/RpiHass/state
2019-09-13 10:44:16 DEBUG (MainThread) [homeassistant.components.mqtt] Subscribing to system-sensors/sensor/RpiHass/state
2019-09-13 10:44:16 DEBUG (MainThread) [homeassistant.components.mqtt] Subscribing to system-sensors/sensor/RpiHass/state
2019-09-13 10:44:16 DEBUG (MainThread) [homeassistant.components.mqtt] Subscribing to system-
```

**Comment by Sennevds** [comment] 2019-09-13 08:45
Could you send me your script? Normally if you restart you should get something like this:
```log
Received message on homeassistant/sensor/DomoPi/DomoPiTemp/config (retained):
```
If hass doesn't see the config message it doesn't recognize the sensor

**Comment by chatainsim** [comment] 2019-09-13 09:05
ok, my mistake, seems I'm not using the latest version of the script.
I'll update and try again.

**Comment by chatainsim** [comment] 2019-09-13 09:11
```
pi@hassbian:~/system_sensors/src $ more system_sensors.py

#!/usr/bin/env python3
from subprocess import check_output
from re import findall
import psutil
import sys
import os
import threading, time, signal
from datetime import timedelta
import datetime as dt
import paho.mqtt.client as mqtt
import pytz
from pytz import timezone



UTC = pytz.utc
DEFAULT_TIME_ZONE = timezone('Europe/Brussels')#Local Time zone
broker_url = "192.168.1.248"#MQTT server IP
broker_port = 1883 #MQTT server port
client = mqtt.Client()
client.username_pw_set("username", "password") #Username and pass if configured otherwise you should comment out this
deviceName = "RpiHass" #Name of your PI
SYSFILE = '/sys/devices/platform/soc/soc:firmware/get_throttled'
WAIT_TIME_SECONDS = 60

class ProgramKilled(Exception):
    pass

def signal_handler(signum, frame):
    raise ProgramKilled

class Job(threading.Thread):
    def __init__(self, interval, execute, *args, **kwargs):
        threading.Thread.__init__(self)
        self.daemon = False
        self.stopped = threading.Event()
        self.interval = interval
        self.execute = execute
        self.args = args
        self.kwargs = kwargs

    def stop(self):
                self.stopped.set()
                self.join()
    def run(self):
            while not self.stopped.wait(self.interval.total_seconds()):
                self.execute(*self.args, **self.kwargs)

def utc_from_timestamp(timestamp: float) -> dt.datetime:
    """Return a UTC time from a timestamp."""
    return UTC.localize(dt.datetime.utcfromtimestamp(timestamp))

def as_local(dattim: dt.datetime) -> dt.datetime:
    """Convert a UTC datetime object to local time zone."""
    if dattim.tzinfo == DEFAULT_TIME_ZONE:
        return dattim
    if dattim.tzinfo is None:
        dattim = UTC.localize(dattim)

    return dattim.astimezone(DEFAULT_TIME_ZONE)

def get_last_boot():
    return str(as_local(utc_from_timestamp(psutil.boot_time())).isoformat())

def updateSensors():
   client.publish(topic="system-sensors/sensor/"+ deviceName +"/state", payload='{"temperature": '+ get_temp() +', "disk_use": '+ get_disk_usage() + ', "memory_us

e": '+ get_memory_usage() +', "cpu_usage": '+ get_cpu_usage() +', "swap_usage": '+ get_swap_usage() +', "power_status": "'+ get_rpi_power_status() +'", "last_boot

": "'+ get_last_boot() +'"}', qos=1, retain=False)

def get_temp():
    temp = check_output(["vcgencmd","measure_temp"]).decode("UTF-8")
    return str(findall("\d+\.\d+",temp)[0])

def get_disk_usage():
    return str(psutil.disk_usage('/').percent)

def get_memory_usage():
    return str(psutil.virtual_memory().percent)

def get_cpu_usage():
    return str(psutil.cpu_percent(interval=None))

def get_swap_usage():
    return str(psutil.swap_memory().percent)

def get_rpi_power_status():
    _throttled = open(SYSFILE, 'r').read()[:-1]
    _throttled = _throttled[:4]
    if _throttled == '0':
        return 'Everything is working as intended'
    elif _throttled == '1000':
        return 'Under-voltage was detected, consider getting a uninterruptible power supply for your Raspberry Pi.'
    elif _throttled == '2000':
        return 'Your Raspberry Pi is limited due to a bad powersupply, replace the power supply cable or power supply itself.'
    elif _throttled == '3000':
        return 'Your Raspberry Pi is limited due to a bad powersupply, replace the power supply cable or power supply itself.'
    elif _throttled == '4000':
        return 'The Raspberry Pi is throttled due to a bad power supply this can lead to corruption and instability, please replace your changer and cables.'
    elif _throttled == '5000':
        return 'The Raspberry Pi is throttled due to a bad power supply this can lead to corruption and instability, please replace your changer and cables.'
    elif _throttled == '8000':
        return 'Your Raspberry Pi is overheating, consider getting a fan or heat sinks.'
    else:
        return 'There is a problem with your power supply or system.'


if __name__ == "__main__":
    signal.signal(signal.SIGTERM, signal_handler)
    signal.signal(signal.SIGINT, signal_handler)
    client.connect(broker_url, broker_port)
    client.publish(topic="homeassistant/sensor/"+ deviceName +"/"+ deviceName +"Temp/config", payload='{"name":"'+ deviceName +'Temperature","state_topic":"system

-sensors/sensor/'+ deviceName +'/state","unit_of_measurement":"°C","value_template":"{{ value_json.temperature}}","unique_id":"'+ deviceName.lower() +'_sensor_tem
p
erature","device":{"identifiers":["'+ deviceName.lower() +'_sensor"],"name":"'+ deviceName +'Sensors","model":"RPI '+ deviceName +'","manufacturer":"RPI"}}', qos=

1, retain=True)
    client.publish(topic="homeassistant/sensor/"+ deviceName +"/"+ deviceName +"DiskUse/config", payload='{"name":"'+ deviceName +'DiskUse","state_topic":"system-

sensors/sensor/'+ deviceName +'/state","unit_of_measurement":"%","value_template":"{{ value_json.disk_use}}","unique_id":"'+ deviceName.lower() +'_sensor_disk_use

","device":{"identifiers":["'+ deviceName.lower() +'_sensor"],"name":"'+ deviceName +'Sensors","model":"RPI '+ deviceName +'","manufacturer":"RPI"}}', qos=1, reta

in=True)
    client.publish(topic="homeassistant/sensor/"+ deviceName +"/"+ deviceName +"MemoryUse/config", payload='{"name":"'+ deviceName +'MemoryUse","state_topic":"sys

tem-sensors/sensor/'+ deviceName +'/state","unit_of_measurement":"%","value_template":"{{ value_json.memory_use}}","unique_id":"'+ deviceName.lower() +'_sensor_me

mory_use","device":{"identifiers":["'+ deviceName.lower() +'_sensor"],"name":"'+ deviceName +'Sensors","model":"RPI '+ deviceName +'","manufacturer":"RPI"}}', qos

=1, retain=True)
    client.publish(topic="homeassistant/sensor/"+ deviceName +"/"+ deviceName +"CpuUsage/config", payload='{"name":"'+ deviceName +'CpuUsage","state_topic":"syste

m-sensors/sensor/'+ deviceName +'/state","unit_of_measurement":"%","value_template":"{{ value_json.cpu_usage}}","unique_id":"'+ deviceName.lower() +'_sensor_cpu_u

sage","device":{"identifiers":["'+ deviceName.lower() +'_sensor"],"name":"'+ deviceName +'Sensors","model":"RPI '+ deviceName +'","manufacturer":"RPI"}}', qos=1,

retain=True)
    client.publish(topic="homeassistant/sensor/"+ deviceName +"/"+ deviceName +"SwapUsage/config", payload='{"name":"'+ deviceName +'SwapUsage","state_topic":"sys

tem-sensors/sensor/'+ deviceName +'/state","unit_of_measurement":"%","value_template":"{{ value_json.swap_usage}}","unique_id":"'+ deviceName.lower() +'_sensor_sw

ap_usage","device":{"identifiers":["'+ deviceName.lower() +'_sensor"],"name":"'+ deviceName +'Sensors","model":"RPI '+ deviceName +'","manufacturer":"RPI"}}', qos

=1, retain=True)
    client.publish(topic="homeassistant/sensor/"+ deviceName +"/"+ deviceName +"PowerStatus/config", payload='{"name":"'+ deviceName +'PowerStatus","state_topic":

"system-sensors/sensor/'+ deviceName +'/state","value_template":"{{ value_json.power_status}}","unique_id":"'+ deviceName.lower() +'_sensor_power_status","device"

:{"identifiers":["'+ deviceName.lower() +'_sensor"],"name":"'+ deviceName +'Sensors","model":"RPI '+ deviceName +'","manufacturer":"RPI"}}', qos=1, retain=True)
    client.publish(topic="homeassistant/sensor/"+ deviceName +"/"+ deviceName +"LastBoot/config", payload='{"device_class":"timestamp","name":"'+ deviceName +'Las

tBoot","state_topic":"system-sensors/sensor/'+ deviceName +'/state","value_template":"{{ value_json.last_boot}}","unique_id":"'+ deviceName.lower() +'_sensor_last

_boot","device":{"identifiers":["'+ deviceName.lower() +'_sensor"],"name":"'+ deviceName +'Sensors","model":"RPI '+ deviceName +'","manufacturer":"RPI"}}', qos=1,

 retain=True)
    job = Job(interval=timedelta(seconds=WAIT_TIME_SECONDS), execute=updateSensors)
    job.start()
    client.loop_forever()

    while True:
            try:
                time.sleep(1)
            except ProgramKilled:
                print ("Program killed: running cleanup code")
                sys.stdout.flush()
                job.stop()
                break
```

**Comment by Sennevds** [comment] 2019-09-13 09:37
Okay that looks good! Can you connect with mqtt explorer(or something similar) and check for following topics:
homeassistant/sensor/RpiHass/RpiHassTemp/config
homeassistant/sensor/RpiHass/RpiHassDiskUse/config
homeassistant/sensor/RpiHass/RpiHassMemoryUse/config
homeassistant/sensor/RpiHass/RpiHassCpuUsage/config
homeassistant/sensor/RpiHass/RpiHassSwapUsage/config
homeassistant/sensor/RpiHass/RpiHassPowerStatus/config
homeassistant/sensor/RpiHass/RpiHassLastBoot/config

these topics should all exist for eacht rpi

**Comment by chatainsim** [comment] 2019-09-13 10:32
Ok, I've sub to #
So when the script is running, only topics system-sensors/sensor/RpiHass/state is updated.
homeassistant/sensor/RpiHass/RpiHass[***]/config is updated only if I restart the script.

I've only restarted one of the script and the other still update system-sensors/sensor/Rpi[***]/state but not homeassistant/sensor/RpiHass/RpiHass[***]/config


![image](https://user-images.githubusercontent.com/1167931/64856553-80d22a80-d622-11e9-8528-81d67a4e1fac.png)

**Comment by Sennevds** [comment] 2019-09-13 10:37
The config topics shouldn't update while running it only updates at startup.
But they should be retained(if you connect to the broker and subscribe to # you should see them without restarting the script)

**Comment by chatainsim** [comment] 2019-09-13 10:41
Ok, so they are not retained, maybe it's something with RabbitMQ then.
I'll dig into this.

**Comment by Sennevds** [comment] 2019-09-13 11:35
I've looked into RabbitMQ(I use Mosquitto) and it looks like you need to enable retained messages:
https://www.rabbitmq.com/mqtt.html#retained

**Comment by chatainsim** [comment] 2019-09-16 07:10
Ok, so I don't kown ho to setup this.
I've try multiple thing be doesn't seems to work.
So I've add this in the script:
```
def updateSensors():
   client.publish(topic="homeassistant/sensor/"+ deviceName +"/"+ deviceName +"Temp/config", payload='{"name":"'+ deviceName +'Temperature","state_topic":"system-

sensors/sensor/'+ deviceName +'/state","unit_of_measurement":"°C","value_template":"{{ value_json.temperature}}","unique_id":"'+ deviceName.lower() +'_sensor_temp
e
rature","device":{"identifiers":["'+ deviceName.lower() +'_sensor"],"name":"'+ deviceName +'Sensors","model":"RPI '+ deviceName +'","manufacturer":"RPI"}}', qos=1

, retain=True)
   client.publish(topic="homeassistant/sensor/"+ deviceName +"/"+ deviceName +"DiskUse/config", payload='{"name":"'+ deviceName +'DiskUse","state_topic":"system-s

ensors/sensor/'+ deviceName +'/state","unit_of_measurement":"%","value_template":"{{ value_json.disk_use}}","unique_id":"'+ deviceName.lower() +'_sensor_disk_use"

,"device":{"identifiers":["'+ deviceName.lower() +'_sensor"],"name":"'+ deviceName +'Sensors","model":"RPI '+ deviceName +'","manufacturer":"RPI"}}', qos=1, retai

n=True)
   client.publish(topic="homeassistant/sensor/"+ deviceName +"/"+ deviceName +"MemoryUse/config", payload='{"name":"'+ deviceName +'MemoryUse","state_topic":"syst

em-sensors/sensor/'+ deviceName +'/state","unit_of_measurement":"%","value_template":"{{ value_json.memory_use}}","unique_id":"'+ deviceName.lower() +'_sensor_mem

ory_use","device":{"identifiers":["'+ deviceName.lower() +'_sensor"],"name":"'+ deviceName +'Sensors","model":"RPI '+ deviceName +'","manufacturer":"RPI"}}', qos=

1, retain=True)
   client.publish(topic="homeassistant/sensor/"+ deviceName +"/"+ deviceName +"CpuUsage/config", payload='{"name":"'+ deviceName +'CpuUsage","state_topic":"system

-sensors/sensor/'+ deviceName +'/state","unit_of_measurement":"%","value_template":"{{ value_json.cpu_usage}}","unique_id":"'+ deviceName.lower() +'_sensor_cpu_us

age","device":{"identifiers":["'+ deviceName.lower() +'_sensor"],"name":"'+ deviceName +'Sensors","model":"RPI '+ deviceName +'","manufacturer":"RPI"}}', qos=1, r

etain=True)
   client.publish(topic="homeassistant/sensor/"+ deviceName +"/"+ deviceName +"SwapUsage/config", payload='{"name":"'+ deviceName +'SwapUsage","state_topic":"syst

em-sensors/sensor/'+ deviceName +'/state","unit_of_measurement":"%","value_template":"{{ value_json.swap_usage}}","unique_id":"'+ deviceName.lower() +'_sensor_swa

p_usage","device":{"identifiers":["'+ deviceName.lower() +'_sensor"],"name":"'+ deviceName +'Sensors","model":"RPI '+ deviceName +'","manufacturer":"RPI"}}', qos=

1, retain=True)
   client.publish(topic="homeassistant/sensor/"+ deviceName +"/"+ deviceName +"PowerStatus/config", payload='{"name":"'+ deviceName +'PowerStatus","state_topic":"

system-sensors/sensor/'+ deviceName +'/state","value_template":"{{ value_json.power_status}}","unique_id":"'+ deviceName.lower() +'_sensor_power_status","device":

{"identifiers":["'+ deviceName.lower() +'_sensor"],"name":"'+ deviceName +'Sensors","model":"RPI '+ deviceName +'","manufacturer":"RPI"}}', qos=1, retain=True)
   client.publish(topic="homeassistant/sensor/"+ deviceName +"/"+ deviceName +"LastBoot/config", payload='{"device_class":"timestamp","name":"'+ deviceName +'Last

Boot","state_topic":"system-sensors/sensor/'+ deviceName +'/state","value_template":"{{ value_json.last_boot}}","unique_id":"'+ deviceName.lower() +'_sensor_last_

boot","device":{"identifiers":["'+ deviceName.lower() +'_sensor"],"name":"'+ deviceName +'Sensors","model":"RPI '+ deviceName +'","manufac
   client.publish(topic="system-sensors/sensor/"+ deviceName +"/state", payload='{"temperature": '+ get_temp() +', "disk_use": '+ get_disk_usage() + ', "memory_us

```
I know, this is ugly but for now it's my temporary bugfixe :)

**Comment by Sennevds** [comment] 2019-09-18 14:07
@chatainsim I'm going to close this topic because I think the problem is with your broker and not with this script!

**Closed by Sennevds** 2019-09-18 14:07 UTC

**Comment by chatainsim** [comment] 2019-09-18 14:30
Yes, sure. Thanks for the help!
