### ISSUE TITLE
Updates Pending Not Updating

### ISSUE THREAD

**Issue by cdn4lf** [Sennevds/system_sensors#92] opened 2021-06-11 12:08 UTC
The number of available updates is no longer updating.  If I manually run `sudo apt update` or `sudo apt upgrade`, the number of updated will populate, however without manually running this no available updates are displayed

**Comment by MaxVRAM** [comment] 2021-08-31 06:09
What system are you running this on? Also, could you please share your settings.yaml and command you use to run the script?

**Comment by cdn4lf** [comment] 2021-08-31 06:27
I got this working. The app is case sensitive in the settings field, but that's not something that's listed anywhere.

**Comment by MaxVRAM** [comment] 2021-08-31 06:45
Thanks for the information. Was this in the field name of the setting or the value for the setting?

**Comment by cdn4lf** [comment] 2021-08-31 11:24
I believe it's check updates. I'd put in a pr bro force lower, but haven't done that part yet.

**Comment by MaxVRAM** [comment] 2021-08-31 11:39
@cdn4lf  thanks for that. Just added a commit to my PR that should prevent letter case of the keys in the settings file from being an issue. It simple converts all the imported keys from the settings file to lowercase to check against.

#104

**Comment by MaxVRAM** [comment] 2021-08-31 11:44
@Sennevds  this issue could be renamed to "Incorrect case of key string in settings file causes setting to be ignored".

This issue can be closed if my PR works as intended and merged into the codebase.

**Comment by cdn4lf** [comment] 2021-08-31 12:32
The True/False on rpi_bad_power and apt_update has a capital letter in the sensors.py file.  I found this didn't match to the settings.yaml file where it is listed as all lower.

**Comment by MaxVRAM** [comment] 2021-08-31 14:50
Are you getting an error or is the script crashing? 

It's true that the case for `true/false` in the settings file doesn't match the Python boolean format of uppercase T/F in the scripts. However, `yaml.safe_load` imports these values in the correct format for Python to read as booleans.

```
>>> file = yaml.safe_load(open('src/settings.yaml'))
>>> print(str(file))
{'mqtt': {'hostname': '192.168.20.3', 'port': 1883, 'user': 'mqtt', 'password': 'super_secret!'}, 'deviceName': 'pi, 'client_id': 'pi', 'timezone': 'Australia/Melbourne', 'update_interval': 30, 'sensors': {'temperature': True, 'clock_speed': True, 'disk_use': True, 'memory_use': True, 'cpu_usage': True, 'load_1m': True, 'load_5m': True, 'load_15m': True, 'net_tx': True, 'net_rx': True, 'swap_usage': True, 'power_status': True, 'last_boot': True, 'hostname': True, 'host_ip': True, 'host_os': True, 'host_arch': True, 'last_message': True, 'updates': True, 'wifi_strength': False, 'wifi_ssid': False, 'external_drives': None}}
```

Note that the parser correctly types the values; ints are not bound within string ' ' quotes, and boolean values are capitalised. Python reads these values as expected.

Ultimately, case shouldn't matter for the boolean values in the settings.yaml. Let me know if this isn't the case on your end.

**Comment by cdn4lf** [comment] 2021-08-31 14:59
Neither.  I just wasn't getting updates.  So the script would run properly, and everything would work, but it would read it as apt_update <> True and not continue.  It felt like it was reading text instead of the boolean value.

**Closed** 2021-11-05 12:33 UTC
